### ISSUE TITLE
Chapter4. Socket backlog issue

### ISSUE THREAD

**Issue by 1ilsang** [Road-of-CODEr/tcp-ip-hot-blood#7]
![image](https://user-images.githubusercontent.com/23524849/113585549-5530ee00-9667-11eb-9aef-3ab605e76224.png)

```c
if(listen(serv_sock, 5)==-1)
```

[예제 코드](https://github.com/Road-of-CODEr/tcp-ip-hot-blood/blob/master/codes/Chapter04%20%EC%86%8C%EC%8A%A4%EC%BD%94%EB%93%9C/echo_server.c#L38)에서 `backLog` 가 5개 까지이지만 실제로는 8번 째에서 커넥트 에러가 나는 것을 확인.

이유가 뭐지? 

cc. @ehddnr8813

**Comment by ehddnr8813** [comment]
@aegis1920

**Comment by 1ilsang** [comment]
생코에 질문했으나 묵묵부답

https://www.facebook.com/groups/codingeverybody/permalink/5614850951888728

**Comment by 1ilsang** [comment]
![image](https://user-images.githubusercontent.com/23524849/114365796-c3206c80-9bb5-11eb-8d05-e8e93231ada6.png)

저자님한테 다이렉트로 질문. 답변 기다리는 중

**Comment by 1ilsang** [comment]
https://stackoverflow.com/questions/5111040/listen-ignores-the-backlog-argument

backLog 인수는 "권고사항" 일 뿐이지 "반드시" 는 아니라고 한다. 이 때문에 안되는 듯?

**Comment by ehddnr8813** [comment]
우선 errno를 확인해봤는데  111번 이더군요. **connection timeout**이더군요, 아래링크를 확인해봤을 때

https://stackoverflow.com/questions/11585377/python-socket-error-errno-111-connection-refused

server 측에서 무언가의 이유로 accept를 못했습니다.
netstat 상에서도 syn_sent상태이지 ack를 받지 못해 established하지 못했습니다,

![이미지 011](https://user-images.githubusercontent.com/40758072/114546037-aceadd00-9c97-11eb-9cce-b78d670ca85f.png)

**결론부터 말하자면 코드의 while안에 read와 write가 있습니다.**
**system call  함수들은 대부분 blocking 함수입니다.**

그런데, 코드를 잘보면 , while문 안에 read와 write를 하고 있습니다. 즉 한 번 연결을 맺었을 때, echo_server에서 한 클라이언트와 write중 block되어있기 때문에 다른 클라이언트들에게 write를 할 수 없습니다.

클라이언트2번이 message를 받기 위해선 기존 client1과 연결을 끊어야 합니다.

![이미지 013](https://user-images.githubusercontent.com/40758072/114544612-d7d43180-9c95-11eb-90ae-5a46d12bed11.png)

이 때문에, server에서 connect client 1 이후로 증가하지 않는 것을 볼 수 있습니다.

server의 backLog를 10으로 바꾼 후 테스트 해보았는데요,

첫 번째부터 열 번 째까지 client 들의 순서대로 끊어야만 10개의 정상 연결을 맺을 수 있습니다. 그리고11번째는 server가 종료되니 더 이상 accept하지 않습니다.

![이미지 015](https://user-images.githubusercontent.com/40758072/114545553-0ef71280-9c97-11eb-857b-4663534ca8e6.png)


@1ilsang for loop에서 write에서 blocking되었기 때문에 client에서 마치 connect된 것처럼 착각한게 맞나요? 사실 서버단에서 5번 맺고 종료되어야 정상입니다...
backlog를 10으로 고쳤더니, 11번째에서 blocking 당하는데, backlog가 5일때 왜 8번째 client에서 blocking 당하는지 아직 모르겠습니다..

**Comment by ehddnr8813** [comment]
이건 번외인데, 
time wait 소켓 재사용, 및 syn_flooding관련 tcp_syncookies on/off 등등, tcp 관련 설정을 코드가 아닌 커널단에서도 수정가능합니다.
tcp_recycle은 deprecated되었기 때문에 더이상 사용하지 않습니다.


![이미지 016](https://user-images.githubusercontent.com/40758072/114547311-41097400-9c99-11eb-8f44-925594f8534e.png)

**Comment by 1ilsang** [comment]
Good
